theme: jekyll-theme-cayman
title: [Real Time Data Analysis]
description: [This repository corresponds to the course Real Time Data Analysis being taught at the Barcelona Technology School by the instructor Ankit Tewari]
